apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fastapi-app-dev
namespace: default
resources:
- ../../base
- virtualservice.yaml
- gateway.yaml
patchesStrategicMerge:
- deployment-patch.yaml
commonLabels:
  environment: dev
  app.kubernetes.io/instance: dev
images:
- name: fastapi-app
  newName: 992382364873.dkr.ecr.us-east-1.amazonaws.com/kargo-argocd
  newTag: 6772512f73e9c03505cb1a5254846ede535b3537
