apiVersion: v1
kind: Secret
metadata:
  name: litellm-db-secret
  namespace: litellm
type: Opaque
stringData:
  username: "postgres"
  password: "Skye12luna3$"  # TODO: Consider using sealed-secrets for production
  host: "litellm1-instance-1.cmru28caiqsp.us-east-1.rds.amazonaws.com"
