apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: litellm-dev
spec:
  hosts:
  - litellm-dev.hamedstock.com
  gateways:
  - litellm-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: litellm
        port:
          number: 4000
