apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fastapi-app-stg
namespace: default
resources:
- ../../base
- virtualservice.yaml
- gateway.yaml
patchesStrategicMerge:
- deployment-patch.yaml
commonLabels:
  environment: stg
  app.kubernetes.io/instance: stg
images:
- name: fastapi-app
  newName: 992382364873.dkr.ecr.us-east-1.amazonaws.com/kargo-argocd
  newTag: e80e1e2b6a870ae25251bd74234fe747875cf5bd
