# Label Outputs
output "label_id" {
  description = "The complete label ID"
  value       = module.label.id
}

output "label_namespace" {
  description = "Normalized namespace"
  value       = module.label.namespace
}

output "label_environment" {
  description = "Normalized environment"
  value       = module.label.environment
}

output "label_name" {
  description = "Normalized name"
  value       = module.label.name
}

output "label_tags" {
  description = "Normalized tags"
  value       = module.label.tags
}

# EKS Cluster Outputs
output "cluster_id" {
  description = "The ID of the EKS cluster"
  value       = module.eks_cluster.eks_cluster_id
}

output "cluster_arn" {
  description = "The ARN of the EKS cluster"
  value       = module.eks_cluster.eks_cluster_arn
}

output "cluster_name" {
  description = "The name of the EKS cluster"
  value       = local.cluster_name
}

output "cluster_endpoint" {
  description = "The endpoint URL of the EKS cluster"
  value       = module.eks_cluster.eks_cluster_endpoint
}

output "cluster_version" {
  description = "The Kubernetes version of the EKS cluster"
  value       = module.eks_cluster.eks_cluster_version
}

output "cluster_platform_version" {
  description = "The Kubernetes version of the EKS cluster"
  value       = module.eks_cluster.eks_cluster_version
}

# Cluster Security
output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks_cluster.eks_cluster_certificate_authority_data
  sensitive   = true
}

output "cluster_security_group_id" {
  description = "ID of the cluster security group"
  value       = module.eks_cluster.eks_cluster_managed_security_group_id
}

output "cluster_primary_security_group_id" {
  description = "ID of the cluster managed security group"
  value       = module.eks_cluster.eks_cluster_managed_security_group_id
}

output "worker_security_group_id" {
  description = "ID of the worker nodes security group"
  value       = aws_security_group.eks_workers_additional.id
}

# OIDC Provider
output "oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = module.eks_cluster.eks_cluster_identity_oidc_issuer
}

output "oidc_provider_arn" {
  description = "The ARN of the OIDC Provider for IRSA"
  value       = module.eks_cluster.eks_cluster_identity_oidc_issuer_arn
}

# Node Groups
output "node_groups" {
  description = "Map of node group attributes"
  value = {
    for k, v in module.eks_node_groups : k => {
      arn            = v.eks_node_group_arn
      id             = v.eks_node_group_id
      status         = v.eks_node_group_status
      instance_types = v.eks_node_group_instance_types
      ami_type       = v.eks_node_group_ami_type
      node_role_arn  = v.eks_node_group_role_arn
    }
  }
}

# IAM Role ARNs for IRSA
output "aws_load_balancer_controller_role_arn" {
  description = "ARN of the AWS Load Balancer Controller IAM role"
  value       = var.environment_config.enable_aws_load_balancer_controller ? module.aws_load_balancer_controller_irsa_role[0].iam_role_arn : null
}

output "cluster_autoscaler_role_arn" {
  description = "ARN of the Cluster Autoscaler IAM role"
  value       = var.environment_config.enable_cluster_autoscaler ? module.cluster_autoscaler_irsa_role[0].iam_role_arn : null
}

output "external_dns_role_arn" {
  description = "ARN of the External DNS IAM role"
  value       = var.environment_config.enable_external_dns ? module.external_dns_irsa_role[0].iam_role_arn : null
}

# Kubeconfig
output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = {
    apiVersion      = "v1"
    kind            = "Config"
    current_context = local.cluster_name
    contexts = [{
      name = local.cluster_name
      context = {
        cluster = local.cluster_name
        user    = local.cluster_name
      }
    }]
    clusters = [{
      name = local.cluster_name
      cluster = {
        server                     = module.eks_cluster.eks_cluster_endpoint
        certificate_authority_data = module.eks_cluster.eks_cluster_certificate_authority_data
      }
    }]
    users = [{
      name = local.cluster_name
      user = {
        exec = {
          apiVersion = "client.authentication.k8s.io/v1beta1"
          command    = "aws"
          args = [
            "eks",
            "get-token",
            "--cluster-name",
            module.eks_cluster.eks_cluster_id,
            "--region",
            var.aws_region
          ]
        }
      }
    }]
  }
  sensitive = true
}

# Cluster Add-ons
output "cluster_addons" {
  description = "Map of cluster addon attributes"
  value = {
    for addon_name, addon_config in var.cluster_addons : addon_name => {
      arn               = addon_config.service_account_role_arn
      addon_version     = addon_config.addon_version
      resolve_conflicts = addon_config.resolve_conflicts_on_update
    }
  }
}

# Remote state reference for other modules
output "remote_state_key" {
  description = "S3 key for remote state - use this in data.terraform_remote_state"
  value       = "terraform/eks/${var.environment}/terraform.tfstate"
}

output "remote_state_config" {
  description = "Complete remote state configuration for other modules"
  value = {
    backend = "s3"
    config = {
      bucket = var.vpc_remote_state_bucket
      key    = "terraform/eks/${var.environment}/terraform.tfstate"
      region = var.aws_region
    }
  }
}

# Application deployment configuration
output "application_config" {
  description = "Configuration values needed for application deployment"
  value = {
    cluster_name       = local.cluster_name
    cluster_endpoint   = module.eks_cluster.eks_cluster_endpoint
    region             = var.aws_region
    vpc_id             = local.vpc_id
    private_subnet_ids = local.private_subnet_ids
    public_subnet_ids  = local.public_subnet_ids

    # IRSA role ARNs for common applications
    irsa_roles = {
      aws_load_balancer_controller = var.environment_config.enable_aws_load_balancer_controller ? module.aws_load_balancer_controller_irsa_role[0].iam_role_arn : null
      cluster_autoscaler           = var.environment_config.enable_cluster_autoscaler ? module.cluster_autoscaler_irsa_role[0].iam_role_arn : null
      external_dns                 = var.environment_config.enable_external_dns ? module.external_dns_irsa_role[0].iam_role_arn : null
    }
  }
}

# Summary output for easy reference
output "cluster_summary" {
  description = "Summary of the EKS cluster configuration"
  value = {
    cluster_name      = local.cluster_name
    cluster_version   = module.eks_cluster.eks_cluster_version
    cluster_endpoint  = module.eks_cluster.eks_cluster_endpoint
    environment       = var.environment
    region            = var.aws_region
    node_groups_count = length(var.node_groups)
    vpc_id            = local.vpc_id
    irsa_enabled      = var.environment_config.enable_irsa

    # Feature flags
    features = {
      cluster_autoscaler           = var.environment_config.enable_cluster_autoscaler
      aws_load_balancer_controller = var.environment_config.enable_aws_load_balancer_controller
      external_dns                 = var.environment_config.enable_external_dns
      cluster_encryption           = var.environment_config.enable_cluster_encryption
    }
  }
}
