apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: litellm-secrets
    app.kubernetes.io/part-of: kargo-argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hamedhaddadian/kargo-argocd
    targetRevision: main
    path: k8s/litellm/base
    kustomize:
      namePrefix: ""
      nameSuffix: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: litellm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
